---
- name: 'node_exporter'
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: 'Create node_exporter user'
      user:
        name: "{{ node_exporter_user }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        create_home: false

    - name: 'Create node_exporter config dir'
      file:
        path: "{{ node_exporter_dir_conf }}"
        state: directory
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"

    - name: 'Download and unzip node_exporter if not exist'
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes
        validate_certs: no

    - name: move the binary to the final destination
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_bin }}"
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        mode: 0755
        remote_src: yes

    - name: 'Remove temporary files'
      file:
        path: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/
        state: absent

    - name: 'Install service'
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0755
      notify: reload_daemon_and_restart_node_exporter

    - meta: flush_handlers

    - name: 'Service always started'
      systemd:
        name: node_exporter
        state: started
        enabled: yes

  handlers:
    - name: 'reload_daemon_and_restart_node_exporter'
      systemd:
        name: node_exporter
        state: restarted
        daemon_reload: yes
        enabled: yes

  vars:
    node_exporter_version: "1.5.0"
    node_exporter_bin: /usr/local/bin/node_exporter
    node_exporter_user: node-exporter
    node_exporter_group: "{{ node_exporter_user }}"
    node_exporter_dir_conf: /etc/node_exporter

